service: basicapp
image: kolosek/basicapp
servers:
  - 5.161.63.224
registry:
  username: kolosek
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
builder:
  multiarch: false
volumes:
  - "~/basic/public:/rails/public"
 labels:
   traefik.http.routers.hey.rule: Host(\'basic.kolosek.me\'')