service: basicapp
image: kolosek/basicapp
servers:
  web:
    - 5.161.63.224
    traefik:
      host_port: 81
registry:
  username: kolosek
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
builder:
  multiarch: false
labels:
   traefik.http.routers.hey.rule: Host(\'basic.kolosek.me\'')
